version: "3.8"

services:
  redis:
    image: redis:7
    container_name: howdens-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance/db.sqlite
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - backend_data:/app/instance
    networks:
      - app-network
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:
  redis_data:

networks:
  app-network:
    driver: bridge
